# setting the Theme to Merlot and simply accessing it remotely. This is the "default" layout
remote_theme: pages-themes/merlot@v0.2.0

# Enabling remote Theme formatting access
plugins:
- jekyll-remote-theme

# setting the site title and description for the page template layouts
title: "LavaCon 2023 - A KB Doesn't Have to Be a KO"
description: "A template repository to jump-start writing big with a tiny team."
