remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: LavaCon 2023: A KB Doesn't Have to Be a KO
description: A template repository to jump-start writing big with a tiny team.
