on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Auto Status Labeler
        uses: peaceiris/actions-label-commenter@v1.10.0
        with:
          PROJECT: ${{ env.PROJECT }}
          COLUMN: ${{ env.PR_COLUMN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

